import { GameStatus, Pokemon, Badge, Battle, AIAction, GameEvent } from './supabase';

// Mock Game Status - Claude está jogando!
export const mockGameStatus: GameStatus = {
    id: 'main',
    is_running: true,
    current_location: 'VIRIDIAN FOREST',
    current_map_id: 51,
    player_x: 23,
    player_y: 18,
    badges: 1,
    pokedex_caught: 12,
    pokedex_seen: 28,
    money: 4850,
    play_time_seconds: 7834, // ~2h10m
    total_battles: 47,
    total_catches: 12,
    current_objective: 'Atravessar Viridian Forest para chegar em Pewter City',
    ai_mood: 'FOCUSED',
    last_action: 'Derrotou Bug Catcher com Pikachu',
    last_screenshot_url: '/game-screen.png',
    updated_at: new Date().toISOString(),
};

// Mock Pokemon Team
export const mockTeam: Pokemon[] = [
    {
        id: '1',
        slot: 1,
        pokedex_number: 25,
        nickname: 'SPARKY',
        species: 'Pikachu',
        level: 18,
        current_hp: 42,
        max_hp: 48,
        attack: 32,
        defense: 22,
        sp_attack: 38,
        sp_defense: 28,
        speed: 52,
        exp: 1847,
        exp_to_next: 2197,
        status: 'OK',
        move_1: 'Thunder Shock',
        move_1_pp: 25,
        move_2: 'Quick Attack',
        move_2_pp: 28,
        move_3: 'Tail Whip',
        move_3_pp: 30,
        move_4: 'Thunder Wave',
        move_4_pp: 15,
        sprite_url: null,
        is_shiny: false,
        caught_location: 'Viridian Forest',
        caught_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '2',
        slot: 2,
        pokedex_number: 1,
        nickname: null,
        species: 'Bulbasaur',
        level: 14,
        current_hp: 44,
        max_hp: 44,
        attack: 24,
        defense: 26,
        sp_attack: 32,
        sp_defense: 32,
        speed: 23,
        exp: 1120,
        exp_to_next: 1331,
        status: 'OK',
        move_1: 'Tackle',
        move_1_pp: 32,
        move_2: 'Growl',
        move_2_pp: 40,
        move_3: 'Leech Seed',
        move_3_pp: 10,
        move_4: 'Vine Whip',
        move_4_pp: 20,
        sprite_url: null,
        is_shiny: false,
        caught_location: 'Pallet Town',
        caught_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '3',
        slot: 3,
        pokedex_number: 16,
        nickname: null,
        species: 'Pidgey',
        level: 12,
        current_hp: 32,
        max_hp: 36,
        attack: 22,
        defense: 20,
        sp_attack: 18,
        sp_defense: 18,
        speed: 28,
        exp: 890,
        exp_to_next: 1000,
        status: 'OK',
        move_1: 'Tackle',
        move_1_pp: 35,
        move_2: 'Sand Attack',
        move_2_pp: 15,
        move_3: 'Gust',
        move_3_pp: 30,
        move_4: null,
        move_4_pp: null,
        sprite_url: null,
        is_shiny: false,
        caught_location: 'Route 1',
        caught_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '4',
        slot: 4,
        pokedex_number: 10,
        nickname: null,
        species: 'Caterpie',
        level: 8,
        current_hp: 26,
        max_hp: 26,
        attack: 14,
        defense: 18,
        sp_attack: 12,
        sp_defense: 12,
        speed: 22,
        exp: 340,
        exp_to_next: 512,
        status: 'OK',
        move_1: 'Tackle',
        move_1_pp: 35,
        move_2: 'String Shot',
        move_2_pp: 40,
        move_3: null,
        move_3_pp: null,
        move_4: null,
        move_4_pp: null,
        sprite_url: null,
        is_shiny: false,
        caught_location: 'Viridian Forest',
        caught_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
];

// Mock Badges
export const mockBadges: Badge[] = [
    { id: '1', badge_name: 'Boulder Badge', badge_number: 1, gym_leader: 'Brock', gym_location: 'Pewter City', pokemon_type: 'Rock', obtained: true, obtained_at: new Date(Date.now() - 3600000).toISOString(), attempts: 2 },
    { id: '2', badge_name: 'Cascade Badge', badge_number: 2, gym_leader: 'Misty', gym_location: 'Cerulean City', pokemon_type: 'Water', obtained: false, obtained_at: null, attempts: 0 },
    { id: '3', badge_name: 'Thunder Badge', badge_number: 3, gym_leader: 'Lt. Surge', gym_location: 'Vermilion City', pokemon_type: 'Electric', obtained: false, obtained_at: null, attempts: 0 },
    { id: '4', badge_name: 'Rainbow Badge', badge_number: 4, gym_leader: 'Erika', gym_location: 'Celadon City', pokemon_type: 'Grass', obtained: false, obtained_at: null, attempts: 0 },
    { id: '5', badge_name: 'Soul Badge', badge_number: 5, gym_leader: 'Koga', gym_location: 'Fuchsia City', pokemon_type: 'Poison', obtained: false, obtained_at: null, attempts: 0 },
    { id: '6', badge_name: 'Marsh Badge', badge_number: 6, gym_leader: 'Sabrina', gym_location: 'Saffron City', pokemon_type: 'Psychic', obtained: false, obtained_at: null, attempts: 0 },
    { id: '7', badge_name: 'Volcano Badge', badge_number: 7, gym_leader: 'Blaine', gym_location: 'Cinnabar Island', pokemon_type: 'Fire', obtained: false, obtained_at: null, attempts: 0 },
    { id: '8', badge_name: 'Earth Badge', badge_number: 8, gym_leader: 'Giovanni', gym_location: 'Viridian City', pokemon_type: 'Ground', obtained: false, obtained_at: null, attempts: 0 },
];

// Mock Recent Battles
export const mockBattles: Battle[] = [
    {
        id: '1',
        battle_type: 'trainer',
        opponent_name: 'Bug Catcher Rick',
        opponent_pokemon: ['Weedle', 'Caterpie'],
        my_pokemon_used: ['Pikachu'],
        result: 'win',
        pokemon_caught: null,
        exp_gained: 156,
        money_gained: 96,
        location: 'Viridian Forest',
        turns: 4,
        ai_strategy: 'Thunder Shock spam - super efetivo contra Flying/Bug',
        created_at: new Date(Date.now() - 120000).toISOString(),
    },
    {
        id: '2',
        battle_type: 'wild',
        opponent_name: null,
        opponent_pokemon: ['Pikachu'],
        my_pokemon_used: ['Bulbasaur'],
        result: 'catch',
        pokemon_caught: 'Pikachu',
        exp_gained: 89,
        money_gained: 0,
        location: 'Viridian Forest',
        turns: 6,
        ai_strategy: 'Enfraquecer com Vine Whip, paralyze com status, capturar com Poke Ball',
        created_at: new Date(Date.now() - 600000).toISOString(),
    },
    {
        id: '3',
        battle_type: 'gym',
        opponent_name: 'Brock',
        opponent_pokemon: ['Geodude', 'Onix'],
        my_pokemon_used: ['Bulbasaur', 'Pikachu'],
        result: 'win',
        pokemon_caught: null,
        exp_gained: 892,
        money_gained: 1386,
        location: 'Pewter City Gym',
        turns: 12,
        ai_strategy: 'Bulbasaur com Vine Whip 4x efetivo. Leech Seed para sustain. Vitoria facil.',
        created_at: new Date(Date.now() - 3600000).toISOString(),
    },
    {
        id: '4',
        battle_type: 'wild',
        opponent_name: null,
        opponent_pokemon: ['Rattata'],
        my_pokemon_used: ['Pidgey'],
        result: 'win',
        pokemon_caught: null,
        exp_gained: 45,
        money_gained: 0,
        location: 'Route 2',
        turns: 3,
        ai_strategy: 'Gust spam para treinar Pidgey',
        created_at: new Date(Date.now() - 5400000).toISOString(),
    },
];

// Mock AI Actions
export const mockActions: AIAction[] = [
    {
        id: '1',
        action_type: 'battle',
        action_detail: 'Usou Thunder Shock em Weedle',
        reasoning: 'Weedle e tipo Bug/Poison. Electric e neutro mas Thunder Shock tem STAB com Pikachu. One-shot garantido pelo nivel.',
        screenshot_before: null,
        screenshot_after: null,
        success: true,
        created_at: new Date(Date.now() - 30000).toISOString(),
    },
    {
        id: '2',
        action_type: 'explore',
        action_detail: 'Moveu para CIMA',
        reasoning: 'Objetivo: sair da Viridian Forest. Caminho norte leva a saida. Evitando grass para nao encontrar wilds desnecessarios.',
        screenshot_before: null,
        screenshot_after: null,
        success: true,
        created_at: new Date(Date.now() - 60000).toISOString(),
    },
    {
        id: '3',
        action_type: 'battle',
        action_detail: 'Iniciou batalha com Bug Catcher',
        reasoning: 'Trainer no caminho, batalha inevitavel. Pikachu na frente para exp. Trainer tem apenas bugs - facil.',
        screenshot_before: null,
        screenshot_after: null,
        success: true,
        created_at: new Date(Date.now() - 90000).toISOString(),
    },
    {
        id: '4',
        action_type: 'menu',
        action_detail: 'Trocou Pikachu para slot 1',
        reasoning: 'Pikachu tem Speed alto e Thunder Shock. Ideal para limpar Viridian Forest rapidamente.',
        screenshot_before: null,
        screenshot_after: null,
        success: true,
        created_at: new Date(Date.now() - 180000).toISOString(),
    },
    {
        id: '5',
        action_type: 'heal',
        action_detail: 'Usou Potion em Bulbasaur',
        reasoning: 'Bulbasaur com 12/44 HP. Preciso dele saudavel para gym battles. Potion restaura 20 HP.',
        screenshot_before: null,
        screenshot_after: null,
        success: true,
        created_at: new Date(Date.now() - 300000).toISOString(),
    },
];

// Mock Events
export const mockEvents: GameEvent[] = [
    {
        id: '1',
        event_type: 'badge',
        title: 'Boulder Badge Conquistada!',
        description: 'Derrotei Brock apos 2 tentativas. Bulbasaur foi o MVP com Vine Whip.',
        pokemon_involved: 'Bulbasaur',
        location: 'Pewter City Gym',
        screenshot_url: null,
        created_at: new Date(Date.now() - 3600000).toISOString(),
    },
    {
        id: '2',
        event_type: 'catch',
        title: 'Pikachu Capturado!',
        description: 'Encontrei um Pikachu raro na Viridian Forest! Taxa de encontro de apenas 5%.',
        pokemon_involved: 'Pikachu',
        location: 'Viridian Forest',
        screenshot_url: null,
        created_at: new Date(Date.now() - 600000).toISOString(),
    },
    {
        id: '3',
        event_type: 'milestone',
        title: 'Jornada Iniciada',
        description: 'Recebi meu primeiro Pokemon do Professor Oak. Escolhi Bulbasaur pela vantagem contra os dois primeiros gyms.',
        pokemon_involved: 'Bulbasaur',
        location: 'Pallet Town',
        screenshot_url: null,
        created_at: new Date(Date.now() - 7200000).toISOString(),
    },
];

// Simulated action messages for terminal
export const terminalMessages = [
    { type: 'system', message: 'Claude AI conectado ao emulador mGBA' },
    { type: 'system', message: 'ROM carregada: Pokemon Fire Red (USA)' },
    { type: 'ai', message: 'Analisando tela... Estou na Viridian Forest' },
    { type: 'ai', message: 'Objetivo atual: Chegar em Pewter City' },
    { type: 'move', message: 'Movendo CIMA - caminho livre detectado' },
    { type: 'battle', message: '! Encontro com trainer Bug Catcher' },
    { type: 'ai', message: 'Avaliando time inimigo: Weedle Lv8, Caterpie Lv8' },
    { type: 'ai', message: 'Estrategia: Pikachu com Thunder Shock' },
    { type: 'battle', message: 'PIKACHU usou THUNDER SHOCK!' },
    { type: 'battle', message: 'E super efetivo!' },
    { type: 'battle', message: 'Weedle inimigo desmaiou!' },
    { type: 'ai', message: 'Proximo: Caterpie. Mantendo estrategia.' },
    { type: 'battle', message: 'PIKACHU usou THUNDER SHOCK!' },
    { type: 'battle', message: 'Caterpie inimigo desmaiou!' },
    { type: 'success', message: 'Vitoria! +156 EXP, +$96' },
    { type: 'ai', message: 'Batalha concluida. Continuando exploracao...' },
];
