import { GameStatus, Pokemon, Badge, Battle, AIAction, GameEvent } from './supabase';

// Mock Game Status - Claude is playing!
export const mockGameStatus: GameStatus = {
    id: 'main',
    is_running: true,
    current_location: 'VIRIDIAN FOREST',
    current_map_id: 51,
    player_x: 23,
    player_y: 18,
    badges: 1,
    pokedex_caught: 12,
    pokedex_seen: 28,
    money: 4850,
    play_time_seconds: 7834, // ~2h10m
    total_battles: 47,
    total_catches: 12,
    current_objective: 'Cross Viridian Forest to reach Pewter City',
    ai_mood: 'FOCUSED',
    last_action: 'Defeated Bug Catcher with Pikachu',
    last_screenshot_url: '/game-screen.png',
    updated_at: new Date().toISOString(),
};

// Mock Pokemon Team
export const mockTeam: Pokemon[] = [
    {
        id: '1',
        slot: 1,
        pokedex_number: 25,
        nickname: 'SPARKY',
        species: 'Pikachu',
        level: 18,
        current_hp: 42,
        max_hp: 48,
        attack: 32,
        defense: 22,
        sp_attack: 38,
        sp_defense: 28,
        speed: 52,
        exp: 1847,
        exp_to_next: 2197,
        status: 'OK',
        move_1: 'Thunder Shock',
        move_1_pp: 25,
        move_2: 'Quick Attack',
        move_2_pp: 28,
        move_3: 'Tail Whip',
        move_3_pp: 30,
        move_4: 'Thunder Wave',
        move_4_pp: 15,
        sprite_url: null,
        is_shiny: false,
        caught_location: 'Viridian Forest',
        caught_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '2',
        slot: 2,
        pokedex_number: 1,
        nickname: null,
        species: 'Bulbasaur',
        level: 14,
        current_hp: 44,
        max_hp: 44,
        attack: 24,
        defense: 26,
        sp_attack: 32,
        sp_defense: 32,
        speed: 23,
        exp: 1120,
        exp_to_next: 1331,
        status: 'OK',
        move_1: 'Tackle',
        move_1_pp: 32,
        move_2: 'Growl',
        move_2_pp: 40,
        move_3: 'Leech Seed',
        move_3_pp: 10,
        move_4: 'Vine Whip',
        move_4_pp: 20,
        sprite_url: null,
        is_shiny: false,
        caught_location: 'Pallet Town',
        caught_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '3',
        slot: 3,
        pokedex_number: 16,
        nickname: null,
        species: 'Pidgey',
        level: 12,
        current_hp: 32,
        max_hp: 36,
        attack: 22,
        defense: 20,
        sp_attack: 18,
        sp_defense: 18,
        speed: 28,
        exp: 890,
        exp_to_next: 1000,
        status: 'OK',
        move_1: 'Tackle',
        move_1_pp: 35,
        move_2: 'Sand Attack',
        move_2_pp: 15,
        move_3: 'Gust',
        move_3_pp: 30,
        move_4: null,
        move_4_pp: null,
        sprite_url: null,
        is_shiny: false,
        caught_location: 'Route 1',
        caught_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '4',
        slot: 4,
        pokedex_number: 10,
        nickname: null,
        species: 'Caterpie',
        level: 8,
        current_hp: 26,
        max_hp: 26,
        attack: 14,
        defense: 18,
        sp_attack: 12,
        sp_defense: 12,
        speed: 22,
        exp: 340,
        exp_to_next: 512,
        status: 'OK',
        move_1: 'Tackle',
        move_1_pp: 35,
        move_2: 'String Shot',
        move_2_pp: 40,
        move_3: null,
        move_3_pp: null,
        move_4: null,
        move_4_pp: null,
        sprite_url: null,
        is_shiny: false,
        caught_location: 'Viridian Forest',
        caught_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
];

// Mock Badges
export const mockBadges: Badge[] = [
    { id: '1', badge_name: 'Boulder Badge', badge_number: 1, gym_leader: 'Brock', gym_location: 'Pewter City', pokemon_type: 'Rock', obtained: true, obtained_at: new Date(Date.now() - 3600000).toISOString(), attempts: 2 },
    { id: '2', badge_name: 'Cascade Badge', badge_number: 2, gym_leader: 'Misty', gym_location: 'Cerulean City', pokemon_type: 'Water', obtained: false, obtained_at: null, attempts: 0 },
    { id: '3', badge_name: 'Thunder Badge', badge_number: 3, gym_leader: 'Lt. Surge', gym_location: 'Vermilion City', pokemon_type: 'Electric', obtained: false, obtained_at: null, attempts: 0 },
    { id: '4', badge_name: 'Rainbow Badge', badge_number: 4, gym_leader: 'Erika', gym_location: 'Celadon City', pokemon_type: 'Grass', obtained: false, obtained_at: null, attempts: 0 },
    { id: '5', badge_name: 'Soul Badge', badge_number: 5, gym_leader: 'Koga', gym_location: 'Fuchsia City', pokemon_type: 'Poison', obtained: false, obtained_at: null, attempts: 0 },
    { id: '6', badge_name: 'Marsh Badge', badge_number: 6, gym_leader: 'Sabrina', gym_location: 'Saffron City', pokemon_type: 'Psychic', obtained: false, obtained_at: null, attempts: 0 },
    { id: '7', badge_name: 'Volcano Badge', badge_number: 7, gym_leader: 'Blaine', gym_location: 'Cinnabar Island', pokemon_type: 'Fire', obtained: false, obtained_at: null, attempts: 0 },
    { id: '8', badge_name: 'Earth Badge', badge_number: 8, gym_leader: 'Giovanni', gym_location: 'Viridian City', pokemon_type: 'Ground', obtained: false, obtained_at: null, attempts: 0 },
];

// Mock Recent Battles
export const mockBattles: Battle[] = [
    {
        id: '1',
        battle_type: 'trainer',
        opponent_name: 'Bug Catcher Rick',
        opponent_pokemon: ['Weedle', 'Caterpie'],
        my_pokemon_used: ['Pikachu'],
        result: 'win',
        pokemon_caught: null,
        exp_gained: 156,
        money_gained: 96,
        location: 'Viridian Forest',
        turns: 4,
        ai_strategy: 'Thunder Shock spam - super effective against Flying/Bug types',
        created_at: new Date(Date.now() - 120000).toISOString(),
    },
    {
        id: '2',
        battle_type: 'wild',
        opponent_name: null,
        opponent_pokemon: ['Pikachu'],
        my_pokemon_used: ['Bulbasaur'],
        result: 'catch',
        pokemon_caught: 'Pikachu',
        exp_gained: 89,
        money_gained: 0,
        location: 'Viridian Forest',
        turns: 6,
        ai_strategy: 'Weaken with Vine Whip, paralyze with status, catch with Poke Ball',
        created_at: new Date(Date.now() - 600000).toISOString(),
    },
    {
        id: '3',
        battle_type: 'gym',
        opponent_name: 'Brock',
        opponent_pokemon: ['Geodude', 'Onix'],
        my_pokemon_used: ['Bulbasaur', 'Pikachu'],
        result: 'win',
        pokemon_caught: null,
        exp_gained: 892,
        money_gained: 1386,
        location: 'Pewter City Gym',
        turns: 12,
        ai_strategy: 'Bulbasaur with Vine Whip 4x effective. Leech Seed for sustain. Easy win.',
        created_at: new Date(Date.now() - 3600000).toISOString(),
    },
    {
        id: '4',
        battle_type: 'wild',
        opponent_name: null,
        opponent_pokemon: ['Rattata'],
        my_pokemon_used: ['Pidgey'],
        result: 'win',
        pokemon_caught: null,
        exp_gained: 45,
        money_gained: 0,
        location: 'Route 2',
        turns: 3,
        ai_strategy: 'Gust spam to train Pidgey',
        created_at: new Date(Date.now() - 5400000).toISOString(),
    },
];

// Mock AI Actions
export const mockActions: AIAction[] = [
    {
        id: '1',
        action_type: 'battle',
        action_detail: 'Used Thunder Shock on Weedle',
        reasoning: 'Weedle is Bug/Poison type. Electric is neutral but Thunder Shock has STAB with Pikachu. One-shot guaranteed by level.',
        screenshot_before: null,
        screenshot_after: null,
        success: true,
        created_at: new Date(Date.now() - 30000).toISOString(),
    },
    {
        id: '2',
        action_type: 'explore',
        action_detail: 'Moved UP',
        reasoning: 'Objective: exit Viridian Forest. North path leads to exit. Avoiding grass to prevent unnecessary wild encounters.',
        screenshot_before: null,
        screenshot_after: null,
        success: true,
        created_at: new Date(Date.now() - 60000).toISOString(),
    },
    {
        id: '3',
        action_type: 'battle',
        action_detail: 'Started battle with Bug Catcher',
        reasoning: 'Trainer in the way, battle unavoidable. Pikachu in front for exp. Trainer only has bugs - easy.',
        screenshot_before: null,
        screenshot_after: null,
        success: true,
        created_at: new Date(Date.now() - 90000).toISOString(),
    },
    {
        id: '4',
        action_type: 'menu',
        action_detail: 'Moved Pikachu to slot 1',
        reasoning: 'Pikachu has high Speed and Thunder Shock. Ideal for clearing Viridian Forest quickly.',
        screenshot_before: null,
        screenshot_after: null,
        success: true,
        created_at: new Date(Date.now() - 180000).toISOString(),
    },
    {
        id: '5',
        action_type: 'heal',
        action_detail: 'Used Potion on Bulbasaur',
        reasoning: 'Bulbasaur at 12/44 HP. Need him healthy for gym battles. Potion restores 20 HP.',
        screenshot_before: null,
        screenshot_after: null,
        success: true,
        created_at: new Date(Date.now() - 300000).toISOString(),
    },
];

// Mock Events
export const mockEvents: GameEvent[] = [
    {
        id: '1',
        event_type: 'badge',
        title: 'Boulder Badge Obtained!',
        description: 'Defeated Brock after 2 attempts. Bulbasaur was the MVP with Vine Whip.',
        pokemon_involved: 'Bulbasaur',
        location: 'Pewter City Gym',
        screenshot_url: null,
        created_at: new Date(Date.now() - 3600000).toISOString(),
    },
    {
        id: '2',
        event_type: 'catch',
        title: 'Pikachu Caught!',
        description: 'Found a rare Pikachu in Viridian Forest! Only 5% encounter rate.',
        pokemon_involved: 'Pikachu',
        location: 'Viridian Forest',
        screenshot_url: null,
        created_at: new Date(Date.now() - 600000).toISOString(),
    },
    {
        id: '3',
        event_type: 'milestone',
        title: 'Journey Started',
        description: 'Received my first Pokemon from Professor Oak. Chose Bulbasaur for the advantage against the first two gyms.',
        pokemon_involved: 'Bulbasaur',
        location: 'Pallet Town',
        screenshot_url: null,
        created_at: new Date(Date.now() - 7200000).toISOString(),
    },
];

// Simulated action messages for terminal
export const terminalMessages = [
    { type: 'system', message: 'Claude AI connected to mGBA emulator' },
    { type: 'system', message: 'ROM loaded: Pokemon Fire Red (USA)' },
    { type: 'ai', message: 'Analyzing screen... I am in Viridian Forest' },
    { type: 'ai', message: 'Current objective: Reach Pewter City' },
    { type: 'move', message: 'Moving UP - clear path detected' },
    { type: 'battle', message: '! Encountered trainer Bug Catcher' },
    { type: 'ai', message: 'Evaluating enemy team: Weedle Lv8, Caterpie Lv8' },
    { type: 'ai', message: 'Strategy: Pikachu with Thunder Shock' },
    { type: 'battle', message: 'PIKACHU used THUNDER SHOCK!' },
    { type: 'battle', message: 'It\'s super effective!' },
    { type: 'battle', message: 'Enemy Weedle fainted!' },
    { type: 'ai', message: 'Next: Caterpie. Maintaining strategy.' },
    { type: 'battle', message: 'PIKACHU used THUNDER SHOCK!' },
    { type: 'battle', message: 'Enemy Caterpie fainted!' },
    { type: 'success', message: 'Victory! +156 EXP, +$96' },
    { type: 'ai', message: 'Battle complete. Continuing exploration...' },
];
